services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URI=${MONGODB_URI}
      - FRONT_URL=${FRONT_URL}
    networks:
      - app-network
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  dokploy-network:
    external: true
